### ISSUE TITLE
Вопрос по кодам статуса

### ISSUE THREAD

**Issue by catamphetamine** [tsunamaru/2ch-wiper#1]
Здравствуйте.
Случайно набрёл на вашу вайпалку, сейчас как раз пишу парсер ответа сервера при отправке сообщения (для проекта другого рода).
Поскольку у 2ch.hk нет нормальной документации, решил заглянуть в ваш код за этим.
https://github.com/tsunamaru/2ch-wiper/blob/70fcffc181d630f202ab9bb421186413d3e3e854/src/engine/main.py
Перечислены коды ошибок:

* `"Error: -6"` — Banned
* `"Error: -4"` — 'access denied' bans
* `"Error: -7"` — Thread closed

Можете уточнить, что они означают?

* `-6` — Что это? Ответ на постинг из запрещённых стран?
* `-4` — Подсеть IP-адресов не из запрещённой страны, но была вручную забанена?
* `-7` — Тред закрыт или удалён? Или только закрыт? Или только удалён?
* Вроде бы больше нет известных кодов ошибок?

**Upd** Ещё вот такой есть:

* `{"Error":-8,"Reason":"Вы постите слишком быстро."}`

**Comment by tsunamaru** [comment]
Доброй ночи.

Из того что помню:
- `-1`: Нет соединения с базой данных (случается редко, когда у макабы падает бэкэнд, либо когда вы отправляете неправильно составленный или сегментированный POST)
- `-3`: В сообщении присутствует слово из спам-листа (не уверен, могу ошибаться с кодом).
- `-4`: Доступ запрещен. Это забаненые подсети из разных стран. С них запрещен постинг везде, кроме /int/. Такие страны у нас перечислены на [отдльной](https://i.imgur.com/aVCXZim.jpg) картинке.
- `-5`: Капча невалидна.
- `-6`: Это регулярные баны. Могут быть как локальными, на одной доске (можно узнать по соотв. приписке в причине бана, например `//!b`), так и глобальными (на всю доску).
- `-7`: Тред закрыт. Нет, он не удален, а именно закрыт. При удаленном треде возвращается стандартное 404.
- `-8`: Вы постите слишком быстро. Стандартный КД на отправку постов во всех досках -- 20 секунд, на создание тредов в /b -- 20 секунд, в тематиках -- 300 секунд. Тут стоит уточнить: КД на создание тредов работает не так, как у обычных постов, а несколько иначе. Он распространяется не на конкретный IP адрес, а вообще на всех. То есть если кто-то создал тред в /b -- в следующие 20 секунд у всех постеров будет выбивать `-8` при попытке создать ещё один, вне зависимости от их адреса. То же самое действует и в тематиках.
- `-13`: Вы запостили слишком много файлов (при попытке отправить более 4х прикреплений в посте без пасскода)
- `-15`: Слишком длинное сообщение (при попытке отправить пост длинной >15000 символов)
- `-20`: Вы ничего не запостили (при попытке отправить пустое сообщение).

**Comment by tsunamaru** [comment]
Ещё вспомнил такой код:

- `{'Error':-2, 'Reason': 'Доска не существует.'}`

Возникает, если отправлен неполный или неверно составленный boundary в заголовке вместе с прикреплениями.

**Comment by catamphetamine** [comment]
@tsunamaru Ого, офигеть, вам даже не лень было всё это писать )
Ваще мужик, братан )

![https://bratan.org/images/muzhik.png](https://bratan.org/images/muzhik.png)

Добавил в документацию:
https://github.com/catamphetamine/chanchan/blob/master/docs/2ch.hk/API.md#%D0%BF%D0%BE%D1%81%D1%82%D0%B8%D0%BD%D0%B3

Хороший у вас подход к делу, и даже несколько аниме-тян прикрутили. 👍

**Comment by tsunamaru** [comment]
Всегда пожалуйста. Порылся у себя ещё немного и нашел старый скриншот:

![изображение](https://user-images.githubusercontent.com/37580200/55693860-00940300-59ba-11e9-83b9-73878a2ddb4f.png)

Подправил свой пост.

**Comment by catamphetamine** [comment]
Обновление: проверил код для ошибки спам-листа — это `-16`.

![image](https://user-images.githubusercontent.com/477167/55726510-a1b1a680-5a18-11e9-8d95-3d8876142888.png)

Так что `-3` — это что-то другое (без разницы).

**Comment by tsunamaru** [comment]
@catamphetamine ещё одно нашел.

![изображение](https://user-images.githubusercontent.com/37580200/56322969-21571800-6173-11e9-923d-60a5ebd3361d.png)

Пост отредактировал.
P.S.: `usercode` -- это уникальный ID постера, который записывается в печеньку после первого поста, а `code` -- пасскод.

**Comment by catamphetamine** [comment]
> ещё одно нашел.

Ок, добавлю в список.

> P.S.: `usercode` -- это уникальный ID постера, который записывается в печеньку после первого поста, а `code` -- пасскод.

Ммм, уникальный ID постера...
Хз, для чего его могут использовать.
Мб для какой-то статистики.

**Comment by catamphetamine** [comment]
> "Вы загружаете одинаковые файлы."

А в каких случаях выдаётся такая ошибка?
Например, если отправляется с некоего IP-адреса одно сообщение, а потом — с того же IP-адреса, второе сообщение, содержащее картинку с тем же `md5` хешем, что и у какой-нибудь из картинок предыдущего (щих?) поста?

**Comment by tsunamaru** [comment]
По ID выдают баны, при заходе с плохой печенькой в тред выскакивает бордер с вот этой мартышкой и воспроизводится очень противный крик.

![изображение](https://user-images.githubusercontent.com/37580200/56323918-f6ba8e80-6175-11e9-941e-840666bcedb5.png)

**Comment by tsunamaru** [comment]
Одинаковые файлы выдаются, если отправлять их в одном посте. На последующие сообщения не распространяется (можно отправить второй пост с идентичным файлом, но только не в одном посте сразу).

В куклоскрипте для обхода этого есть (была?) функция в настройках -- уникальный хэш для каждого прикрепления в посте.

**Comment by catamphetamine** [comment]
> По ID выдают баны, при заходе с плохой печенькой в тред выскакивает бордер с вот этой мартышкой и воспроизводится очень противный крик.

ммм, прикольно )
судя по всему, имеется ввиду куки `usercode_auth`.
я тестировал пару раз отправку сообщения в тред (и создание треда): в обоих случаях отправляемое значение `usercode` было пустым, так что я пока оставлю `???` в документации (до выяснения).

**Comment by catamphetamine** [comment]
> я тестировал пару раз отправку сообщения в тред (и создание треда): в обоих случаях отправляемое значение `usercode` было пустым.

Ну да, поле `usercode`, судя по всему, не используется: попробовал ответить в 18+ раздел — поле осталось пустым.

![image](https://user-images.githubusercontent.com/477167/56326215-da225480-617d-11e9-891c-6c3638875cbb.png)

**Comment by catamphetamine** [comment]
@tsunamaru 

> P.S.: usercode -- это уникальный ID постера, который записывается в печеньку после первого поста, а code -- пасскод. Если передаётся поле с пасскодом, ЕМНИП, captcha_type отправлять не обязательно.

Так, я разобрался: `code` — всегда пустое, `usercode` — хеш пасскода (не сам пасскод).
https://github.com/catamphetamine/chanchan/blob/master/docs/2ch.hk/API.md#%D0%BF%D0%B0%D1%81%D1%81%D0%BA%D0%BE%D0%B4

**Comment by tsunamaru** [comment]
> usercode — хеш пасскода (не сам пасскод).  

Вы правы. Я перепутал с куками из-за похожих названий :)
