### ISSUE TITLE
При попытке запустить вылетает

### ISSUE THREAD

**Issue by justaregularwiper** [tsunamaru/2ch-wiper#2]
У меня windows 7 x64. Установил питон, скачал вайпалку. При попытке запуска сначала вот такая ошибка:
![photo_2019-06-02_13-05-44](https://user-images.githubusercontent.com/51293516/58763182-44d9f480-8560-11e9-9a18-3920d8be3d94.jpg)
Потом вот такая:
![photo_2019-06-02_13-06-18](https://user-images.githubusercontent.com/51293516/58763186-4e635c80-8560-11e9-89f8-37d2b206b03f.jpg)

**Comment by tsunamaru** [comment]
Русские символы в пути до папки с `wiper_win32.exe` есть?

**Comment by justaregularwiper** [comment]
Спасибо, теперь все нормально.
