### ISSUE TITLE
Отсутствие бибилиотеки под Linux

### ISSUE THREAD

**Issue by desup6** [tsunamaru/2ch-wiper#4]
Последняя версия, не хватает libicui18n.so.63, в /lib оной не обнаружено

**Comment by tsunamaru** [comment]
Похоже что Вы пользуетесь очень старой системой без поддержки Юникода. Попробуйте установить `libicu` из своего пакетного менеджера.

**Comment by desup6** [comment]
libcu стоит, система не старая, версия ядра - последняя стабильная. Пока копаюсь, откатываясь на разные версии.

**Comment by tsunamaru** [comment]
Пересобрал без поодержки Юникода, попробуйте запустить.

[wiper_linux64.zip](https://github.com/tsunamaru/2ch-wiper/files/3356891/wiper_linux64.zip)

**Comment by desup6** [comment]
В пересобранном та же ошибка. Выяснилось, что бибиотека-таки в наличии, вот только версия более поздняя - 64.2. В поисках способа даунгрейднуться

**Comment by tsunamaru** [comment]
Симлинк сделать, не?

**Comment by desup6** [comment]
Решил проще: `downgrade icu`.  Спасибо за классную вайпалку и подтянутые знания линукса!
